### ISSUE TITLE
step task: :method_name doesn't work

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-activity-dsl-linear#11]
You can't specify a `:method` when using the macro style.

```ruby
step task: :some_instance_method
```

throws an error.

**Comment by apotonick** [comment]
As noted in the docs: http://2019.trailblazer.to/2.1/docs/activity.html#activity-internals-circuit-interface-dsl Everything `task: ...` is receiving the **circuit interface** not the step interface. Good spotting! :pray:

**Comment by yogeshjain999** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [step task: :method_name doesn't work](https://trello.com/c/RxiR92OI/100-step-task-methodname-doesnt-work)
