### ISSUE TITLE
Ruby 2.7 -> warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

### ISSUE THREAD

**Issue by andreyagra** [trailblazer/trailblazer-activity-dsl-linear#25]
Hi guys,

I know it's warnings, but it's disturbing a lot... Any action for that (Rails 6.0.3.2)?

`/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:124: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:127: warning: The called method `append_end_options' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:183: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:138: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:154: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:164: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:135: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:137: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:160: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:134: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
[Declarative] Defaults#merge! and #call still accept arrays and automatically prepend those. This is now deprecated, you should replace `ary` with `Declarative::Variables::Append(ary)`.
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:33: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/strategy.rb:30: warning: The called method `false' is defined here
/usr/local/bundle/gems/trailblazer-activity-0.10.1/lib/trailblazer/activity/circuit.rb:45: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-0.10.1/lib/trailblazer/activity/circuit.rb:27: warning: The called method `call' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/strategy.rb:34: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:175: warning: The called method `apply_adds_from_dsl' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:177: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:15: warning: The called method `create_row' is defined here
/usr/local/bundle/gems/active_hash-3.1.0/lib/associations/associations.rb:22: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/associations.rb:1657: warning: The called method `belongs_to' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:137: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/normalizer.rb:194: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:15: warning: The called method `create_row' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:124: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:127: warning: The called method `append_end_options' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:183: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:138: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/path.rb:154: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:164: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:135: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:137: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:160: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:134: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/fast_track.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
[Declarative] Defaults#merge! and #call still accept arrays and automatically prepend those. This is now deprecated, you should replace `ary` with `Declarative::Variables::Append(ary)`.
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:33: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/strategy.rb:30: warning: The called method `false' is defined here
/usr/local/bundle/gems/trailblazer-activity-0.10.1/lib/trailblazer/activity/circuit.rb:45: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-0.10.1/lib/trailblazer/activity/circuit.rb:27: warning: The called method `call' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/strategy.rb:34: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:175: warning: The called method `apply_adds_from_dsl' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:177: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:15: warning: The called method `create_row' is defined here
/usr/local/bundle/gems/active_hash-3.1.0/lib/associations/associations.rb:22: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/activerecord-6.0.3.2/lib/active_record/associations.rb:1657: warning: The called method `belongs_to' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:137: warning: The called method `OptionsForState' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/railway.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/state.rb:16: warning: The called method `initialize' is defined here
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear/normalizer.rb:194: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/trailblazer-activity-dsl-linear-0.2.8/lib/trailblazer/activity/dsl/linear.rb:15: warning: The called method `create_row' is defined here
`

**Comment by apotonick** [comment]
@andreyagra Waiting for your PR - it's a simple task with great impact! :heart:

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by ljachymczyk** [comment]
+1

**Comment by apotonick** [comment]
0.4.0 onwards is Ruby 3 compatible, so this is fixed. :sunrise: https://github.com/trailblazer/trailblazer-activity-dsl-linear/blob/master/CHANGES.md#040
