### ISSUE TITLE
Receiving a RuntimeError in the face of Rails' reloading

### ISSUE THREAD

**Issue by nickgrim** [trailblazer/trailblazer-activity-dsl-linear#7]
(This may not be the correct repository for this issue, but this is where the code that's throwing the error lives)

I'm using these gems:
```
$ bundle show | grep trailblazer
  * trailblazer (2.1.0.rc1)
  * trailblazer-activity (0.8.2)
  * trailblazer-activity-dsl-linear (0.1.5)
  * trailblazer-cells (0.0.3)
  * trailblazer-context (0.1.2)
  * trailblazer-loader (0.1.2)
  * trailblazer-macro (2.1.0.rc11)
  * trailblazer-macro-contract (2.1.0.rc11)
  * trailblazer-operation (0.5.1)
  * trailblazer-rails (2.1.7)
```

I've got this (toy!) operation:
```
module Argh
  class Alpha < Trailblazer::Operation
    pass :step_alpha
    def step_alpha(ctx, **); end
  end
end
```

…and Things Go Wrong in the face of Rails' code reloading.
Here's a copy of the output from the rails console, but I can also see this backtrace in a browser pointed at `rails s` running in the development environment:
```
$ rails c
Loading development environment (Rails 5.2.3)
irb(main):001:0> reload!
Reloading...
Traceback (most recent call last):
       16: from app/concepts/argh/operation/alpha.rb:1:in `<main>'
       15: from app/concepts/argh/operation/alpha.rb:3:in `<module:Argh>'
       14: from app/concepts/argh/operation/alpha.rb:5:in `<class:Alpha>'
       13: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/fast_track.rb:153:in `pass'
       12: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/dsl/linear/strategy.rb:48:in `recompile_activity_for'
       11: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/railway.rb:125:in `pass'
       10: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/dsl/linear/strategy.rb:32:in `task_for!'
        9: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/dsl/linear/state.rb:25:in `update_sequence'
        8: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/dsl/linear/strategy.rb:34:in `block in task_for!'
        7: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/dsl/linear/state.rb:49:in `call'
        6: from trailblazer-activity (0.8.2) lib/trailblazer/activity/circuit.rb:44:in `call'
        5: from trailblazer-activity (0.8.2) lib/trailblazer/activity/circuit.rb:44:in `loop'
        4: from trailblazer-activity (0.8.2) lib/trailblazer/activity/circuit.rb:45:in `block in call'
        3: from trailblazer-activity (0.8.2) lib/trailblazer/activity/circuit.rb:27:in `block in <class:Circuit>'
        2: from trailblazer-activity (0.8.2) lib/trailblazer/activity/circuit.rb:27:in `call'
        1: from trailblazer-activity-dsl-linear (0.1.5) lib/trailblazer/activity/path.rb:88:in `raise_on_duplicate_id'
RuntimeError (ID step_alpha is already taken. Please specify an `:id`.)
```

As you might expect, changing the code to

    pass :step_alpha, id: 'whatever'

just gives:

    RuntimeError (ID whatever is already taken. Please specify an `:id`.)

after a `reload!`.

----

If it's any help, I've recently updated all of the Trailblazer gems in my project, and this behaviour **didn't** occur with this set:
```
$ bundle show | grep trailblazer
  * trailblazer (2.1.0.rc1)
  * trailblazer-activity (0.7.1)
  * trailblazer-cells (0.0.3)
  * trailblazer-context (0.1.2)
  * trailblazer-loader (0.1.2)
  * trailblazer-macro (2.1.0.rc1)
  * trailblazer-macro-contract (2.1.0.rc1)
  * trailblazer-operation (0.4.1)
  * trailblazer-rails (2.1.7)
```

**Comment by seuros** [comment]
If you want to try the latest RC (RC11), you need to use `gem "trailblazer", github: 'trailblazer/trailblazer'`

**Comment by nickgrim** [comment]
Thanks @seuros. I updated my `Gemfile`, `bundle install`-ed, and I still get the same error as above with these gems:
```
$ bundle show | grep trailblazer
  * trailblazer (2.1.0.rc11 a009c06)
  * trailblazer-activity (0.8.2)
  * trailblazer-activity-dsl-linear (0.1.5)
  * trailblazer-cells (0.0.3)
  * trailblazer-context (0.1.4)
  * trailblazer-loader (0.1.2)
  * trailblazer-macro (2.1.0.rc11)
  * trailblazer-macro-contract (2.1.0.rc11)
  * trailblazer-operation (0.5.1)
  * trailblazer-rails (2.1.7)
```

**Comment by seuros** [comment]
Your namespaceping is wrong 

should be 
```
module Argh::Operation
  class Alpha < Trailblazer::Operation
    pass :step_alpha
    def step_alpha(ctx, **); end
  end
end
```

or move the file to `app/concepts/argh/alpha.rb`

You have to follow Rails convention for naming when using a rails application.

Your code will work on production without any issue even with wrong naming, but you will have hard time with development mode .

**Comment by emaglio** [comment]
Nick has just released a new TRB version, can you please update your gems and check if that still happening?
Are you using the TRB loader?

**Comment by nickgrim** [comment]
@emaglio:
> Nick has just released a new TRB version, can you please update your gems and check if that still happening?

I've updated my gems to the following:
```
$ grep trailblazer Gemfile
gem 'trailblazer', '>= 2.1.0.beta'
# gem 'trailblazer', github: 'trailblazer/trailblazer'
gem 'trailblazer-cells'
gem 'trailblazer-rails'

$ bundle show | grep trailblazer
  * trailblazer (2.1.0.rc12)
  * trailblazer-activity (0.8.3)
  * trailblazer-activity-dsl-linear (0.1.6)
  * trailblazer-cells (0.0.3)
  * trailblazer-context (0.1.4)
  * trailblazer-loader (0.1.2)
  * trailblazer-macro (2.1.0.rc12)
  * trailblazer-macro-contract (2.1.0.rc12)
  * trailblazer-operation (0.5.2)
  * trailblazer-rails (2.1.7)
```

…and with the code at the top (i.e.

    module Argh
      class Alpha < Trailblazer::Operation
      …

), I am still getting the same error.

> Are you using the TRB loader?

Not explicitly; I'm just including `trailblazer-rails` which is pulling it in. I haven't created any special config for it.

----

@seuros:
> Your namespaceping is wrong
> …
> You have to follow Rails convention for naming when using a rails application

Thanks for that; changing the code to:

    module Argh::Operation
      class Alpha < Trailblazer::Operation
      …

…*does* seem to fix the problem!

I was wondering how I'd managed to get-it-so-wrong / make-it-work all this time, and I note that the documentation for `trailblazer-loader` seems to suggest that my initial approach should have worked. 

The [Explicit Singular layout](https://github.com/trailblazer/trailblazer-loader#explicit-singular) says (emphasis mine):

> Per concept, you have one directory per abstraction layer and one file per class. All is singular and 
reflects the namespace (**except for operations which sit in the concept's namespace**).

…and [Namespacing Operations](https://github.com/trailblazer/trailblazer-loader#namespacing-operations) suggests that `app/concepts/comment/create.rb` "contains `Comment::Create`", so I guess that documentation will need updating, unless this is a bug/feature in `trailblazer-loader`?

**Comment by nickgrim** [comment]
To _further_ complicate matters, I've got some other operations in this project that don't have `::Operation` in their namespace, but that aren't affected by this reload bug, e.g. this one that lives at `app/concepts/landing_page/operation/find.rb`:
```ruby
class LandingPage::Find < Trailblazer::Operation
  step :find_landing_page!
  …
end
```

`LandingPage` is an existing class (an `ActiveRecord` subclass), so maybe that's relevant?

**Comment by seuros** [comment]
I personally namespace all my operations inside an operations module and the contracts inside a contracts module.

**Comment by emaglio** [comment]
@nickgrim I have tried your operation on my project and it works fine in both cases (with the correct namespace and the wrong one).
```
bundle show | grep trailblazer
  * trailblazer (2.1.0.rc12)
  * trailblazer-activity (0.8.3)
  * trailblazer-activity-dsl-linear (0.1.6)
  * trailblazer-cells (0.0.3)
  * trailblazer-context (0.1.4)
  * trailblazer-developer (0.0.1)
  * trailblazer-loader (0.1.2)
  * trailblazer-macro (2.1.0.rc12)
  * trailblazer-macro-contract (2.1.0.rc12)
  * trailblazer-operation (0.5.2)
  * trailblazer-rails (2.1.5)
```
`trailblazer-rails` is 2.1.5 but the new minor releases don't have anything important in there.

It must be something specific with your project...do you have some sort of configuration for TRB or something specifically loaded in `config/application.rb`?

**Comment by seuros** [comment]
maybe he has spring.

**Comment by nickgrim** [comment]
@seuros:
> maybe he has spring.

I do have `spring` in the project this example is from. However, I've thrown together a minimal repo (without `spring`) which exhibits the issue at https://github.com/nickgrim/trailblazer-reload-issue. Does that work for y'all?

**Comment by apotonick** [comment]
I think it's our loader combined with autoloading. See here:
http://2019.trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails-loader-loader-with-rails
This explains the recent approach we've been using in a bunch of projects.

**Comment by nickgrim** [comment]
Sorry for disappearing! I didn't fancy trying to work out what the various loaders were doing, so in the end, I just moved all of my operations to live within an `::Operation::` namespace.

**Comment by apotonick** [comment]
@nickgrim Did you also disable the `loader` gem?

Speaking of, @seuros - should we make the loader something optional you have to activate rather then turn off?

**Comment by seuros** [comment]
@apotonick , that the plan. The next major version will have the loader as optional.

**Comment by nickgrim** [comment]
> @nickgrim Did you also disable the loader gem?

Yes, sorry, I did that too.
